@host = https://localhost:7044

POST {{host}}/tokens/generate
Content-Type: application/json

{
    "id": "00000000-0000-0000-0000-111111111111",
    "firstName": "Jesper",
    "lastName": "Gulmann Henriksen",
    "email": "jesper@gulmann.dk",
    "permissions": [
        "create:submission",
        "upload:submission",
        "get:submission",
        "delete:submission",
        "create:vote",
        "get:vote",
        "delete:vote"
    ],
    "roles": [
        "Admin"
    ]
}

### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmVzcGVyIiwiZmFtaWx5X25hbWUiOiJHdWxtYW5uIEhlbnJpa3NlbiIsImVtYWlsIjoiamVzcGVyQGd1bG1hbm4uZGsiLCJpZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTExMTExMTExMTExMSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwicGVybWlzc2lvbnMiOlsiY3JlYXRlOnN1Ym1pc3Npb24iLCJ1cGxvYWQ6c3VibWlzc2lvbiIsImdldDpzdWJtaXNzaW9uIiwiZGVsZXRlOnN1Ym1pc3Npb24iLCJjcmVhdGU6dm90ZSIsImdldDp2b3RlIiwiZGVsZXRlOnZvdGUiXSwiZXhwIjoxNzQ4MTk5NjM4LCJpc3MiOiJOcHVTZXJ2aWNlIiwiYXVkIjoiTnB1U2VydmljZSJ9.VMHM5PtRHvY7Da7ovLkwWWk4OOi973imIomNjxXFGjM

POST {{host}}/tokens/generate
Content-Type: application/json

{
    "id": "00000000-0000-0000-0000-222222222222",
    "firstName": "Noah",
    "lastName": "Kirk Gulmann",
    "email": "noah@gulmann.dk",
    "permissions": [
        "create:submission",
        "upload:submission",
        "get:submission",
        "delete:submission",
        "create:vote",
        "get:vote",
        "delete:vote"
    ],
    "roles": []
}

### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTm9haCIsImZhbWlseV9uYW1lIjoiS2lyayBHdWxtYW5uIiwiZW1haWwiOiJub2FoQGd1bG1hbm4uZGsiLCJpZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTIyMjIyMjIyMjIyMiIsInBlcm1pc3Npb25zIjpbImNyZWF0ZTpzdWJtaXNzaW9uIiwidXBsb2FkOnN1Ym1pc3Npb24iLCJnZXQ6c3VibWlzc2lvbiIsImRlbGV0ZTpzdWJtaXNzaW9uIiwiY3JlYXRlOnZvdGUiLCJnZXQ6dm90ZSIsImRlbGV0ZTp2b3RlIl0sImV4cCI6MTc0ODE5OTY4MywiaXNzIjoiTnB1U2VydmljZSIsImF1ZCI6Ik5wdVNlcnZpY2UifQ.x_Bn2tImNCexoQc24mlC4Ak34T2qmgh76TZ4jZINup8
