@host = https://localhost:7044

POST {{host}}/submissions/0196fdc5-cd8e-7f7a-8ba4-adbbe684848b/votes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmVzcGVyIiwiZmFtaWx5X25hbWUiOiJHdWxtYW5uIEhlbnJpa3NlbiIsImVtYWlsIjoiamVzcGVyQGd1bG1hbm4uZGsiLCJpZCI6IlRva2VuSWQgeyBWYWx1ZSA9IDAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTExMTExMTExMTExMSB9IiwicGVybWlzc2lvbnMiOlsiY3JlYXRlOnN1Ym1pc3Npb24iLCJkZWxldGU6c3VibWlzc2lvbiIsImdldDpzdWJtaXNzaW9uIl0sImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzQ4MDMzMjM1LCJpc3MiOiJOcHVTZXJ2aWNlIiwiYXVkIjoiTnB1U2VydmljZSJ9.0PUpK13BQJhJC-jOIJUrwpAhtHWoVH4pT1tr2p7K2Ag
Content-Type: application/json

{
    "userId": "00000000-0000-0000-0000-111111111111",
    "creativityScore": "5",
    "uniquenessScore": "4"
}

### Admin-only
GET {{host}}/users/00000000-0000-0000-0000-111111111111/submissions/0196fdc5-cd8e-7f7a-8ba4-adbbe684848b/votes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTm9haCIsImZhbWlseV9uYW1lIjoiS2lyayBHdWxtYW5uIiwiZW1haWwiOiJub2FoQGd1bG1hbm4uZGsiLCJpZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTIyMjIyMjIyMjIyMiIsInBlcm1pc3Npb25zIjpbImNyZWF0ZTpzdWJtaXNzaW9uIiwiZGVsZXRlOnN1Ym1pc3Npb24iLCJnZXQ6c3VibWlzc2lvbiJdLCJleHAiOjE3NDgwMzYwMTIsImlzcyI6Ik5wdVNlcnZpY2UiLCJhdWQiOiJOcHVTZXJ2aWNlIn0.BgaqsvjNLfCqPc6GjipOwnYxrPygoMBSOEcrDoCfvPQ
Accept-Type: application/json
