@host = https://localhost:7044

POST {{host}}/users/00000000-0000-0000-0000-111111111111/submissions/0197089d-f207-7a27-94ac-898a39f7f9ae/votes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTm9haCIsImZhbWlseV9uYW1lIjoiS2lyayBHdWxtYW5uIiwiZW1haWwiOiJub2FoQGd1bG1hbm4uZGsiLCJpZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTIyMjIyMjIyMjIyMiIsInBlcm1pc3Npb25zIjpbImNyZWF0ZTpzdWJtaXNzaW9uIiwidXBsb2FkOnN1Ym1pc3Npb24iLCJnZXQ6c3VibWlzc2lvbiIsImRlbGV0ZTpzdWJtaXNzaW9uIiwiY3JlYXRlOnZvdGUiLCJnZXQ6dm90ZSIsImRlbGV0ZTp2b3RlIl0sImV4cCI6MTc0ODE5OTY4MywiaXNzIjoiTnB1U2VydmljZSIsImF1ZCI6Ik5wdVNlcnZpY2UifQ.x_Bn2tImNCexoQc24mlC4Ak34T2qmgh76TZ4jZINup8
Content-Type: application/json

{
    "creativityScore": "1",
    "uniquenessScore": "1"
}

###

POST {{host}}/users/00000000-0000-0000-0000-111111111111/submissions/0196fdc5-cd8e-7f7a-8ba4-adbbe684848b/votes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTm9haCIsImZhbWlseV9uYW1lIjoiS2lyayBHdWxtYW5uIiwiZW1haWwiOiJub2FoQGd1bG1hbm4uZGsiLCJpZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTIyMjIyMjIyMjIyMiIsInBlcm1pc3Npb25zIjpbImNyZWF0ZTpzdWJtaXNzaW9uIiwiZGVsZXRlOnN1Ym1pc3Npb24iLCJnZXQ6c3VibWlzc2lvbiJdLCJleHAiOjE3NDgxNjAxNzAsImlzcyI6Ik5wdVNlcnZpY2UiLCJhdWQiOiJOcHVTZXJ2aWNlIn0.-BaqThcb8rbf170_kggREGKUMwyytSDzb9UK6nZADRk
Content-Type: application/json

{
    "creativityScore": "5",
    "uniquenessScore": "5"
}



###

GET {{host}}/users/00000000-0000-0000-0000-111111111111/submissions/0196fdc5-cd8e-7f7a-8ba4-adbbe684848b/votes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmVzcGVyIiwiZmFtaWx5X25hbWUiOiJHdWxtYW5uIEhlbnJpa3NlbiIsImVtYWlsIjoiamVzcGVyQGd1bG1hbm4uZGsiLCJpZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTExMTExMTExMTExMSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwicGVybWlzc2lvbnMiOlsiY3JlYXRlOnN1Ym1pc3Npb24iLCJkZWxldGU6c3VibWlzc2lvbiIsImdldDpzdWJtaXNzaW9uIl0sImV4cCI6MTc0ODE2MDEyNywiaXNzIjoiTnB1U2VydmljZSIsImF1ZCI6Ik5wdVNlcnZpY2UifQ.LdYCrsERGEBAa2jsKTneIGT5GGcu2fGOaOYWp7H04WU
Accept-Type: application/json
